steps:

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_REGISTRY_BASE}/models:$SHORT_SHA
      - -t
      - ${_REGISTRY_BASE}/models:${_SAFE_BRANCH}
      - '.'
    dir: '.'
    secretEnv: ['API_KEY', 'API_SECRET', 'ACCESS_TOKEN', 'ACCESS_SECRET', 'BEARER_TOKEN', 'CLIENT_ID', 'CLIENT_SECRET']

availableSecrets:
  secretManager:
  - versionName: projects/ml-dev-403200/secrets/twitter_api_key/versions/latest
    env: 'API_KEY'
  - versionName: projects/ml-dev-403200/secrets/twitter_api_secret/versions/latest
    env: 'API_SECRET'
  - versionName: projects/ml-dev-403200/secrets/twitter_access_token/versions/latest
    env: 'ACCESS_TOKEN'
  - versionName: projects/ml-dev-403200/secrets/twitter_access_secret/versions/latest
    env: 'ACCESS_SECRET'
  - versionName: projects/ml-dev-403200/secrets/twitter_bearer_token/versions/latest
    env: 'BEARER_TOKEN'
  - versionName: projects/ml-dev-403200/secrets/twitter_client_id/versions/latest
    env: 'CLIENT_ID'
  - versionName: projects/ml-dev-403200/secrets/twitter_client_secret/versions/latest
    env: 'CLIENT_SECRET'


options:
  dynamic_substitutions: true
images:
  - '${_REGISTRY_BASE}/models:$SHORT_SHA'
  - '${_REGISTRY_BASE}/models:${_SAFE_BRANCH}'
  - '${_REGISTRY_BASE}/dagster-image:$SHORT_SHA'
  - '${_REGISTRY_BASE}/dagster-image:${_SAFE_BRANCH}'
timeout: 500s
substitutions:
  _SAFE_BRANCH: ${BRANCH_NAME//\//-}
  _REGISTRY_BASE: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker

