services:

  dagster-webserver:
    image: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker/dagster-project:develop
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/.dbt:/mnt/dbt
      - ${HOME}/.config/gcloud:/mnt/gcloud
    command: >
      sh -c export GCP_CREDS_JSON_CREDS_BASE64="$(cat /mnt/gcloud/application_default_credentials.json | base64)" &&
            dagster-webserver
  dagster-daemon:
    image: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker/dagster-project:develop
    command: "dagster-daemon run"
    # environment:
    #   - PGPASS=${PGPASS}
    #   - PGUID=${PGUID}

#   dagster-postgres:
#     image: postgres:13.3
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_PASSWORD=${PGPASS}
#     volumes:
#       - dagster-postgres:/var/lib/postgresql/data
# volumes:
#   dagster-postgres:
#     driver: local