services:

  dagster-webserver:
    image: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker/dagster-project:develop
    ports:
      - 3100:3100
    volumes:
      - ${HOME}/.dbt:/mnt/dbt
      - ${HOME}/.config/gcloud:/mnt/gcloud
    command: >
      sh -c "chmod +x ./up.sh &&
             . ./up.sh &&  
             dagster-webserver -w workspace.yaml -h 0.0.0.0 -p 3100 "

  dagster-daemon:
    image: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker/dagster-project:develop
    volumes:
      - ${HOME}/.dbt:/mnt/dbt
      - ${HOME}/.config/gcloud:/mnt/gcloud
    command: >
      sh -c "chmod +x ./up.sh &&
             . ./up.sh &&  
             dagster-daemon run"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'