services:

  dagster_webserver:
    image: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker/dagster-project:develop
    ports:
      - 3100:3100
    volumes:
      - ${HOME}/.dbt:/mnt/dbt
      - ${HOME}/.config/gcloud:/mnt/gcloud
    command: >
      sh -c "chmod +x ./up.sh &&
             . ./up.sh &&  
             dagster-webserver -w workspace.yaml -h 0.0.0.0 -p 3100 "
    environment:
      POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
    networks:
      - docker_network
    depends_on:
      - docker_postgres

  dagster_daemon:
    image: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker/dagster-project:develop
    volumes:
      - ${HOME}/.dbt:/mnt/dbt
      - ${HOME}/.config/gcloud:/mnt/gcloud
    command: >
      sh -c "chmod +x ./up.sh &&
             . ./up.sh &&  
             dagster-daemon run"
    environment:
      POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB}

  docker_postgres:
    image: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker/dagster-postgres:develop #postgres:13.3
    ports:
      - 5432:5432
    networks:
      - docker_network
    container_name: docker_postgres
    environment:
      POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
    volumes:
      - docker_postgres:/var/lib/postgresql/data


  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #    - '3000:3000'

volumes:
  docker_postgres:
    driver: local

networks:
  docker_network:
    driver: bridge
    name: docker_network


# Database is uninitialized and superuser password is not specified. You must specify POSTGRES_PASSWORD to a non-empty value for the
#  superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".