dbt_project:
  outputs:
    dev:
      dataset: SENTIMAX
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /mnt/gcloud/dagster_gcp_key.json
      location: US
      method: service-account
      priority: interactive
      project: ml-dev-403200
      threads: 1
      type: bigquery
  target: dev
